[versions]
agp = "8.5.2"
kotlin = "2.0.20"
####################
activity = "1.9.2"
accompanistInsets = "0.22.0-rc"
annotationJvm = "1.8.2"
appcompat = "1.7.0"
coil = "2.6.0"
composeBom = "2024.08.00"
composeNavigation = "2.7.7"
composeMultiplatform = "1.6.10"
coroutines = "1.8.1"
dataStore = "1.1.1"
detekt = "1.23.5"
detektCompose = "0.3.9"
flowLayout = "0.32.0"
gson = "2.10.1"
hilt = "2.51"
hiltNavigationCompose = "1.2.0"
hiltWork = "1.2.0"
immutableCollections = "0.3.5"
junit5 = "5.9.3"
kluent = "1.72"
koin = "4.0.0-RC2"
ksp = "2.0.20-1.0.24" # change it with kotlin
ktlint = "0.48.2"
ktlintPlugin = "11.6.1"
ktor = "2.3.12"
lifecycle = "2.8.5"
material3 = "1.3.0"
mockk = "1.13.10"
okhttpBom = "4.12.0"
timber = "5.0.1"
room = "2.7.0-alpha07"
sqlite = "2.5.0-alpha06"
turbine = "1.0.0"
workManager = "2.9.1"

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinCocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinParcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintPlugin" }
room = { id = "androidx.room", version.ref = "room" }

[libraries]
accompanistInsets = { module = "com.google.accompanist:accompanist-insets", version.ref = "accompanistInsets" }
annotationJvm = { group = "androidx.annotation", name = "annotation-jvm", version.ref = "annotationJvm" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
composeActivity = { group = "androidx.activity", name = "activity-compose", version.ref = "activity" }
composeBom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
composeCoil = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
composeFlowLayout = { group = "com.google.accompanist", name = "accompanist-flowlayout", version.ref = "flowLayout" }
composeMaterial3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
composeNavigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "composeNavigation" }
composeRuntime = { group = "androidx.compose.runtime", name = "runtime" }
composeTooling = { group = "androidx.compose.ui", name = "ui-tooling" }
coroutinesAndroid = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
coroutinesCore = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
dataStore = { group = "androidx.datastore", name = "datastore-preferences-core", version.ref = "dataStore" }
detektCompose = { group = "io.nlopez.compose.rules", name = "detekt", version.ref = "detektCompose" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
hiltAndroid = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hiltCore = { group = "com.google.dagger", name = "hilt-core", version.ref = "hilt" }
hiltCompiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
hiltNavigationCompose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
koinBom = { group = "io.insert-koin", name = "koin-bom", version.ref = "koin" }
koinCore = { group = "io.insert-koin", name = "koin-core" }
koinAndroid = { group = "io.insert-koin", name = "koin-android" }
koinAndroidCompose = { group = "io.insert-koin", name = "koin-androidx-compose" }
koinCompose = { group = "io.insert-koin", name = "koin-compose" }
koinComposeViewmodel = { group = "io.insert-koin", name = "koin-compose-viewmodel" }
koinWorkManager = { group = "io.insert-koin", name = "koin-androidx-workmanager" }
ktorCore = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktorOkhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktorDarwin = { group = "io.ktor", name = "ktor-client-darwin", version.ref = "ktor" }
ktorContentNegotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktorLogging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
ktorGson = { group = "io.ktor", name = "ktor-serialization-gson", version.ref = "ktor" }
ktorAuth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
immutableCollections = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "immutableCollections" }
lifecycleCompose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }
lifecycleViewModel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp" }
okhttpBom = { group = "com.squareup.okhttp3", name = "okhttp-bom", version.ref = "okhttpBom" }
okhttpLoggingInterceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor" }
roomCompiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
roomKtx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
roomRuntime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
sqlite = { group = "androidx.sqlite", name = "sqlite", version.ref = "sqlite" }
sqliteBundled = { group = "androidx.sqlite", name = "sqlite-bundled", version.ref = "sqlite" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
workManagerHilt = { group = "androidx.hilt", name = "hilt-work", version.ref = "hiltWork" }
workManagerRuntime = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workManager" }
# Test
testCoroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }
testJunitJupiterApi = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit5" }
testJunitKotlin = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit", version.ref = "kotlin" }
testKluent = { group = "org.amshove.kluent", name = "kluent", version.ref = "kluent" }
testKoin = { group = "io.insert-koin", name = "koin-test" }
testKoinJunit5 = { group = "io.insert-koin", name = "koin-test-junit5", version.ref = "koin" }
testMockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
testTurbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }

[bundles]
ktor = [
    "ktorCore",
    "ktorContentNegotiation",
    "ktorAuth",
    "ktorLogging",
    "ktorGson",
]
testCore = [
    "testMockk",
    "testKluent",
    "testTurbine",
    "testCoroutines",
    "testJunitKotlin",
    "testJunitJupiterApi",
]
